#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

setxkbmap es &
bash ~/.config/polybar/launch.sh --forest &
xrandr --output DP-1 --primary --output HDMI-0 --left-of DP-1 &
nitrogen --restore

bspc monitor DP-1 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 6 7 8 9 10

bspc config border_width         0
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
